### ISSUE TITLE
Exception thrown for environments not running Replica Set

### ISSUE THREAD

**Issue by kbbgl** [kbbgl/e2ewd_deployer#2]
```
24/04/2019 05:28:44.371 [main] DEBUG org.mongodb.driver.protocol.command - Execution of command with request id 11 failed to complete successfully in 1.93 ms on connection [connectionId{localValue:2, serverValue:715}] to server localhost:27018
com.mongodb.MongoCommandException: Command failed with error 76 (NoReplicationEnabled): 'not running with --replSet' on server localhost:27018. The full response is {"ok": 0.0, "errmsg": "not running with --replSet", "code": 76, "codeName": "NoReplicationEnabled"}
	at com.mongodb.internal.connection.ProtocolHelper.getCommandFailureException(ProtocolHelper.java:179)
	at com.mongodb.internal.connection.InternalStreamConnection.receiveCommandMessageResponse(InternalStreamConnection.java:299)
	at com.mongodb.internal.connection.InternalStreamConnection.sendAndReceive(InternalStreamConnection.java:255)
	at com.mongodb.internal.connection.UsageTrackingInternalConnection.sendAndReceive(UsageTrackingInternalConnection.java:99)
	at com.mongodb.internal.connection.DefaultConnectionPool$PooledConnection.sendAndReceive(DefaultConnectionPool.java:444)
	at com.mongodb.internal.connection.CommandProtocolImpl.execute(CommandProtocolImpl.java:72)
	at com.mongodb.internal.connection.DefaultServer$DefaultServerProtocolExecutor.execute(DefaultServer.java:200)
	at com.mongodb.internal.connection.DefaultServerConnection.executeProtocol(DefaultServerConnection.java:269)
	at com.mongodb.internal.connection.DefaultServerConnection.command(DefaultServerConnection.java:131)
	at com.mongodb.internal.connection.DefaultServerConnection.command(DefaultServerConnection.java:123)
	at com.mongodb.operation.CommandOperationHelper.executeWrappedCommandProtocol(CommandOperationHelper.java:243)
	at com.mongodb.operation.CommandOperationHelper.executeWrappedCommandProtocol(CommandOperationHelper.java:214)
	at com.mongodb.operation.CommandOperationHelper.executeWrappedCommandProtocol(CommandOperationHelper.java:206)
	at com.mongodb.operation.CommandOperationHelper.executeWrappedCommandProtocol(CommandOperationHelper.java:116)
	at com.mongodb.operation.CommandOperationHelper.executeWrappedCommandProtocol(CommandOperationHelper.java:109)
	at com.mongodb.operation.CommandReadOperation.execute(CommandReadOperation.java:56)
	at com.mongodb.client.internal.MongoClientDelegate$DelegateOperationExecutor.execute(MongoClientDelegate.java:179)
	at com.mongodb.client.internal.MongoClientDelegate$DelegateOperationExecutor.execute(MongoClientDelegate.java:161)
	at com.mongodb.DB.executeCommand(DB.java:774)
	at com.mongodb.DB.command(DB.java:520)
	at com.mongodb.DB.command(DB.java:536)
	at com.mongodb.DB.command(DB.java:491)
	at token.MongoOperations.<init>(MongoOperations.java:38)
	at token.MongoOperations.getInstance(MongoOperations.java:24)
	at tasks.InstallationTask.getToken(InstallationTask.java:226)
	at tasks.InstallationTask.setConfigurationValues(InstallationTask.java:172)
	at tasks.InstallationTask.run(InstallationTask.java:51)
	at App.main(App.java:20)
```

**Comment by kbbgl** [comment]
Fixed in version 1.3.2.
