### ISSUE TITLE
installing 7.4.0.10067 fails with JSONException: JSONObject["webServer.host"] not found

### ISSUE THREAD

**Issue by kbbgl** [kbbgl/e2ewd_deployer#4]
```
org.json.JSONException: JSONObject["webServer.host"] not found.
        at org.json.JSONObject.get(JSONObject.java:566)
        at tasks.InstallationTask.getServerInformation(InstallationTask.java:180
)
        at tasks.InstallationTask.run(InstallationTask.java:56)
        at App.main(App.java:25)
```

**Comment by kbbgl** [comment]
fixed in 1.6.0.
